(part "OPA196IDBVR"
    (packageRef "SOT95P280X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "OUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "V-") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "-IN") (portType INOUT))
        (port "5" (symbPinId 5) (portName "V+") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-OPA196IDBVR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/OPA196IDBVR?qs=EU6FO9ffTwdOeFWwHLQKWg%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "OPA196IDBVR")
    (property "Description" "36V, Low Power, All-Purpose Amplifier with MUX-Friendly Input")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/opa196")
    (property "symbolName1" "OPA196IDBVR")
)
