(part "MCP41HV51-503E_ST"
    (packageRef "SOP65P640X120-14N")
    (interface
        (port "1" (symbPinId 1) (portName "VL") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SCK") (portType INOUT))
        (port "3" (symbPinId 3) (portName "%CS%") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SDI") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SDO") (portType INOUT))
        (port "6" (symbPinId 6) (portName "%WLAT%") (portType INOUT))
        (port "7" (symbPinId 7) (portName "%SHDN%") (portType INOUT))
        (port "8" (symbPinId 8) (portName "NC") (portType INOUT))
        (port "9" (symbPinId 9) (portName "DGND") (portType INOUT))
        (port "10" (symbPinId 10) (portName "V-") (portType INOUT))
        (port "11" (symbPinId 11) (portName "P0B") (portType INOUT))
        (port "12" (symbPinId 12) (portName "P0W") (portType INOUT))
        (port "13" (symbPinId 13) (portName "P0A") (portType INOUT))
        (port "14" (symbPinId 14) (portName "V+") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "579-MCP41HV51-503EST")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology/MCP41HV51-503E-ST?qs=zOnbk8%2FsRx4ZUpOx9fi55g%3D%3D")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "MCP41HV51-503E/ST")
    (property "Description" "MCP41HV51-503E/ST, Digital Potentiometer 50k 256-Position Serial-SPI 14-Pin TSSOP")
    (property "Datasheet_Link" "http://ww1.microchip.com/downloads/en/devicedoc/20005207b.pdf")
    (property "symbolName1" "MCP41HV51-503E_ST")
)
